// auth reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UAUTHENTICATED = "SET_UAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
// UI REDUCER TYPES
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_UI = "LOADING_UI";

export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
// export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
// export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
