# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wissenpos CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master]
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
      
    - name: 🔨 Build Project
      env:
        REACT_APP_STAGE: ${{ secrets.REACT_APP_STAGE }}
        REACT_APP_ME: ${{ secrets.REACT_APP_ME }}
        REACT_APP_FIREBASE_apiKey: ${{ secrets.REACT_APP_FIREBASE_apiKey }}
        REACT_APP_FIREBASE_authDomain: ${{ secrets.REACT_APP_FIREBASE_authDomain }}
        REACT_APP_databaseURL: ${{ secrets.REACT_APP_databaseURL }}
        REACT_APP_FIREBASE_projectId: ${{secrets. REACT_APP_FIREBASE_projectId }}
        REACT_APP_FIREBASE_storageBucket: ${{ secrets.REACT_APP_FIREBASE_storageBucket }}
        REACT_APP_FIREBASE_messagingSenderId: ${{ secrets.REACT_APP_FIREBASE_messagingSenderId }}
        REACT_APP_FIREBASE_appId: ${{ secrets.REACT_APP_FIREBASE_appId }}
        REACT_APP_FIREBASE_measurementId: ${{secrets.REACT_APP_FIREBASE_measurementId}}
        # REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}

      run: |
        yarn install
        yarn run build --if-present
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.wissensof.com
        username: ${{ secrets.pos_username}}
        password: ${{ secrets.pos_password }}
        # protocol: ftps
        # port: 21
       
        






